/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { AdoptionContract } from "./Adoption";
import { ERC165Contract } from "./ERC165";
import { ERC721Contract } from "./ERC721";
import { ERC721URIStorageContract } from "./ERC721URIStorage";
import { IERC165Contract } from "./IERC165";
import { IERC721Contract } from "./IERC721";
import { IERC721MetadataContract } from "./IERC721Metadata";
import { IERC721ReceiverContract } from "./IERC721Receiver";
import { MigrationsContract } from "./Migrations";
import { NFTContract } from "./NFT";
import { PotatoMarketContract } from "./PotatoMarket";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "Adoption"): AdoptionContract;
      require(name: "ERC165"): ERC165Contract;
      require(name: "ERC721"): ERC721Contract;
      require(name: "ERC721URIStorage"): ERC721URIStorageContract;
      require(name: "IERC165"): IERC165Contract;
      require(name: "IERC721"): IERC721Contract;
      require(name: "IERC721Metadata"): IERC721MetadataContract;
      require(name: "IERC721Receiver"): IERC721ReceiverContract;
      require(name: "Migrations"): MigrationsContract;
      require(name: "NFT"): NFTContract;
      require(name: "PotatoMarket"): PotatoMarketContract;
    }
  }
}

export { AdoptionContract, AdoptionInstance } from "./Adoption";
export { ERC165Contract, ERC165Instance } from "./ERC165";
export { ERC721Contract, ERC721Instance } from "./ERC721";
export {
  ERC721URIStorageContract,
  ERC721URIStorageInstance,
} from "./ERC721URIStorage";
export { IERC165Contract, IERC165Instance } from "./IERC165";
export { IERC721Contract, IERC721Instance } from "./IERC721";
export {
  IERC721MetadataContract,
  IERC721MetadataInstance,
} from "./IERC721Metadata";
export {
  IERC721ReceiverContract,
  IERC721ReceiverInstance,
} from "./IERC721Receiver";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
export { NFTContract, NFTInstance } from "./NFT";
export { PotatoMarketContract, PotatoMarketInstance } from "./PotatoMarket";
